RMS/Models/ResultViewModel.cs
using RMSDataModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RMS.Models
{
    public class ResultViewModel
    {
        [Required]
        [Display(Name = "Registration Number")]
        public string RegistrationNumber { get; set; }

        //[Required]
        //[Display(Name = "Department" )]
        //public int DepartmentId { get; set; }
        [Required]
        [Display(Name = "Calender Year")]
        [Range(1900, 2100)]
        public int CalenderYear { get; set; }

        [Required]
        [Display(Name = "Semester/Year")]
        public Semester Semester { get; set; }
    }

}

RMS/Controllers/ResultController.cs
using RMS.Models;
using RMSDataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace RMS.Controllers
{
    [AllowAnonymous]
    public class ResultController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Result
        public ActionResult Index()
        {
            //return View();
            return RedirectToAction("CheckResult");
        }

        // GET: /Result/CheckResult
        [AllowAnonymous]
        public ActionResult CheckResult()
        {
            //ViewBag.ReturnUrl = returnUrl;
            //ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentID", "Name");
            return View();
        }

        //
        // POST: Result/CheckResult
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult CheckResult(ResultViewModel model, string returnUrl)
        {
            //ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentID", "Name");
            if (!ModelState.IsValid)
            {
                return View(model);
            }                     
            
            var student =  db.Students
                .Where(c => (c.RegistrationNumber == model.RegistrationNumber))
                .FirstOrDefault();
            

            if(student == null)
            {
                ModelState.AddModelError("", "Student Not Found");
                return View(model);
                //return HttpNotFound();
            }

            var resultPublications = db.ResultPublications
                .Where(r => r.DepartmentID == student.DepartmentId
                && r.CalenderYear == model.CalenderYear
                && r.Semester == model.Semester).FirstOrDefault();

            if(resultPublications == null)
            {
                ModelState.AddModelError("", "Result is not published yet");
                return View(model);
            }

            var publicationDate = resultPublications.PublicationDate;
            var currentDate = DateTime.Now;


            if(DateTime.Compare(publicationDate,currentDate) > 0 )
            {
                ModelState.AddModelError("", "Result will be published at " + publicationDate.ToString("MMMM dd, yyyy"));
                return View(model);
            }

            var viewmodel = new MarkSheetViewModel();

            viewmodel.Student = student;

            var enrollments = db.Enrollments
                .Where(e => e.StudentId == student.ID && e.Semester == model.Semester).ToList();
            

            if(!enrollments.Any())
            {
                ModelState.AddModelError("", "Result Not Found");
                return View(model);
                //return HttpNotFound();
            }

            viewmodel.Enrollments = enrollments;

            double currentSemesterTotalCredits = 0.0;
            double currentSemesterObtainedCredits = 0.0;

            bool promoted = true;
            foreach (var enrollment in enrollments )
            {
                var credit = enrollment.Course.Credits;
                currentSemesterTotalCredits += credit;
                var gp = enrollment.GradePoint;

                if (gp < student.Department.LeastGPToPass || gp == 0.0)
                {
                    promoted = false;
                }

                currentSemesterObtainedCredits += gp*credit;
            }

            

            double TotalCredits = 0.0;
            double ObtainedCredits = 0.0;

            var allEnrollments = student.Enrollments;

            foreach (var enrollment in allEnrollments)
            {
                var credit = enrollment.Course.Credits;
                TotalCredits += credit;
                ObtainedCredits += enrollment.GradePoint*credit;
            }

            if (ObtainedCredits / TotalCredits < student.Department.LeastCGPAToPass)
                viewmodel.Promoted = false;

            viewmodel.Semester = model.Semester;
            viewmodel.Promoted = promoted;
            viewmodel.CurrentSemesterTotalCredits = currentSemesterTotalCredits;
            viewmodel.CurrentSemesterObtainedCredits = currentSemesterObtainedCredits;
            viewmodel.TotalCredits = TotalCredits;
            viewmodel.TotalObtainedCredits = ObtainedCredits;

            GeneratePdf(viewmodel);

            return View("Transcript", viewmodel);
        }

        //public ActionResult Download(string file)
        //{
        //    if (!System.IO.File.Exists(file))
        //    {
        //        return HttpNotFound();
        //    }

        //    var fileBytes = System.IO.File.ReadAllBytes(file);
        //    var response = new FileContentResult(fileBytes, "application/octet-stream")
        //    {
        //        FileDownloadName = "loremIpsum.pdf"
        //    };
        //    return response;
        //}

        private void GeneratePdf(MarkSheetViewModel viewmodel)
        {
            List<string[]> pdfData = new List<string[]>();

            foreach(var enrollment in viewmodel.Enrollments)
            {
                pdfData.Add(new string[]
                { enrollment.CourseID.ToString(), enrollment.Course.Title,
                enrollment.Course.Credits.ToString(), enrollment.Grade, enrollment.GradePoint.ToString() 
                });
            }
            String registrationNumber = viewmodel.Student.RegistrationNumber;
            String studentname = viewmodel.Student.Name;
            String examName = viewmodel.Student.ExamRoll.ToString();
            String semester = viewmodel.Semester.ToString();
            //new PDFGenerator(pdfData.ToArray(),registrationNumber,examName,studentname,semester);
            new PDFGenerator(pdfData.ToArray(), viewmodel.Student);




        }

        //public ActionResult GenerateMarksheetIndex()
        //{

        //    return View();
        //}

        //public ActionResult GenerateMarksheet()
        //{
        //    var model = new MarkSheetViewModel();
        //    model.Students = db.Students
        //        .Where(s => s.Semester == 0);
        //    model.Courses = db.Courses;

        //    model.Enrollments = db.Enrollments;



        //    return View(model);
        //}
    }
}

RMS/Views/Result/CheckResult.cshtml
@using RMS.Models
@model ResultViewModel

@{
    ViewBag.Title = "CheckResult";
}

<h2>Check Result</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("CheckResult", "Result", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.RegistrationNumber, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.RegistrationNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.RegistrationNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CalenderYear, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CalenderYear, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CalenderYear, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                        @Html.LabelFor(model => model.DepartmentId, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
                        </div>
                    </div>*@


                <div class="form-group">
                    @Html.LabelFor(m => m.Semester, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(m => m.Semester, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Semester, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </div>
                </div>

            }
        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RMS/Views/Result/GenerateMarksheet.cshtml
@model RMS.Models.MarkSheetViewModel
@{
    ViewBag.Title = "GenerateMarksheet";
}

<h2>GenerateMarksheet</h2>

<table class="table">

    @{ var singlStudent = Model.Students.FirstOrDefault();
        var singleEnrollment = Model.Enrollments.FirstOrDefault();}

    <tr>
        <td>
            @Html.DisplayNameFor(item => singlStudent.RegistrationNumber)
        </td>
        <td>
            @Html.DisplayNameFor(item => singlStudent.Name)
        </td>
        @foreach(var item in singlStudent.Enrollments)
        { 
            <td>
                @Html.DisplayFor( i => item.Course.Title)
            </td>
        }
    </tr>

    @foreach (var student in Model.Students)
    {
    <tr>
        <td>
            @Html.DisplayFor(item => student.RegistrationNumber)
        </td>
        <td>
            @Html.DisplayFor(item => student.Name)
        </td>
        @foreach (var enrollment in student.Enrollments)
    {
        <td>
            @Html.DisplayFor(item => enrollment.TotalMark)
        </td>
}
    </tr>
    }


    @*@foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseID)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Course.Title)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Course.Department.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Course.Credits)
                </td>

                <td>
                    @Html.ActionLink("Details", "Details", new { courseID = item.CourseID }) |
                    @Html.ActionLink("Students", "StudentList", new { courseID = item.CourseID }) |
                    @Html.ActionLink("MarkSheet", "MarkSheet", new { assignmentID = item.AssignmentID })
                    @Html.ActionLink("Edit", "Edit", new { id = item.AssignmentID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.AssignmentID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.AssignmentID })
                </td>
            </tr>
        }*@

</table>

RMS/Views/Result/GenerateMarksheetIndex.cshtml
@model RMS.Models.MarkSheetForm
@{
    ViewBag.Title = "GenerateMarksheetIndex";
}

<h2>GenerateMarksheetIndex</h2>

<div class="row">
    <div class="col-md-8">


        <div class="form-group">
            @Html.LabelFor(m => m.Semester, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(m => m.Semester, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Semester, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Year, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Year, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div>
            @Html.ActionLink("Submit", "GenerateMarksheet", new { Semester = Model.Semester, Year = Model.Year})
        </div>*@
        
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RMS/Views/Result/Transcript.cshtml
@model RMS.Models.MarkSheetViewModel
@{
    ViewBag.Title = "Transcript";
}

<h2>Transcript</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Student.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.RegistrationNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.RegistrationNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Session)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Session)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.ExamRoll)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.ExamRoll)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Department.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Department.Name)
        </dd>
    </dl>
</div>

<table class="table table-bordered">
    <tr>
        <th>
            Course Code
        </th>
        <th>
            Course Title
        </th>
        <th>
            Credits
        </th>

        <th>
            Grade
        </th>
        <th>
            Grade Point
        </th>
    </tr>


    @foreach (var enrollment in Model.Enrollments)
    {
        <tr>
            <td>
                @Html.DisplayFor(item => enrollment.CourseID)
            </td>

            <td>
                @Html.DisplayFor(item => enrollment.Course.Title)
            </td>

            <td>
                @Html.DisplayFor(item => enrollment.Course.Credits)
            </td>

            <td>
                @Html.DisplayFor(item => enrollment.Grade)
            </td>
            <td>
                @Html.DisplayFor(item => enrollment.GradePoint)
            </td>
        </tr>
    }

</table>

<table class="table table-bordered">
    <tr>
        <td colspan="6">
            Total Credits
        </td>

        <td rowspan="3">
            Result
        </td>
    </tr>
    <tr>
        <td colspan="2">
            @Model.Semester Semester
        </td>
        <td colspan="2">
            Upto  Previous Semester
        </td>

        <td colspan="2">
            Upto @Model.Semester Semester
        </td>


    </tr>
    <tr>
        <td colspan="2">
            @Model.CurrentSemesterTotalCredits
        </td>
        <td colspan="2">
            @Model.UptoPreviousSemesterTotalCredits
        </td>

        <td colspan="2">
            @Model.TotalCredits
        </td>
    </tr>

    <tr>
        <td>
            @Html.DisplayNameFor(item => Model.CurrentSemesterTotalCredits)
        </td>
        <td>
            @Html.DisplayNameFor(item => Model.CurrentSemesterGPA)
        </td>
        <td>
            @Html.DisplayNameFor(item => Model.UptoPreviousSemesterTotalCredits)
        </td>
        <td>
            @Html.DisplayNameFor(item => Model.UptoPreviousSemesterGPA)
        </td>
        <td>
            @Html.DisplayNameFor(item => Model.TotalCredits)
        </td>
        <td>
            @Html.DisplayNameFor(item => Model.CGPA)
        </td>
        @if (Model.Promoted)
        {
            <td rowspan="2">
                Promoted
            </td>
        }
        else
        {
            <td rowspan="2">
                Not Promoted
            </td>
        }
    </tr>

    <tr>
        <td>
            @Html.DisplayFor(item => Model.CurrentSemesterObtainedCredits)
        </td>
        <td>
            @Html.DisplayFor(item => Model.CurrentSemesterGPA)
        </td>
        <td>
            @Html.DisplayFor(item => Model.UptoPreviousSemesterObtainedCredits)
        </td>
        <td>
            @Html.DisplayFor(item => Model.UptoPreviousSemesterGPA)
        </td>
        <td>
            @Html.DisplayFor(item => Model.TotalObtainedCredits)
        </td>
        <td>
            @Html.DisplayFor(item => Model.CGPA)
        </td>
    </tr>

</table>

@{
    var filename = Model.Student.RegistrationNumber + ".pdf";
}
<div id="test">

    <a href="~/Transcripts/@filename" target="_blank" class="btn btn-info btn-md">Download</a>
</div>
<br>
<button onclick="myFunction()">Print this page</button>

<script>
    function myFunction() {
        window.print();
    }
</script>